

sshpass -p "nJ0:DHze7@}kf=V" ssh ed_fraser@34.39.19.192 -Yes

sqlcmd -S localhost -E "SELECT 'DATA SOURCE=localhost;INITIAL CATALOG=' + DB_NAME() + CASE TYPE_DESC WHEN 'WINDOWS_LOGIN' THEN ';TRUSTED_CONNECTION=TRUE' ELSE ';USER ID=sa;PASSWORD=mZ6=hnPh' END AS CONNECTIONSTRING FROM SYS.SERVER_PRINCIPALS WHERE NAME =sa"



DATA SOURCE=inst-install-sql-2022-web-windows-2022-dc-build-build-sq-v70xy;INITIAL CATALOG=master;USER ID=sa;PASSWORD=<<YOURPASSWORD>>